name: Frontend CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # ex: netvolutionfr/voyages-front

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (facultatif) Lint rapide – non bloquant au début
      - name: Lint (non-bloquant)
        run: |
          npm ci || true
          npm run lint --if-present || true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,priority=800
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image (VITE_* en build-args)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_API_BASE=${{ vars.VITE_API_BASE }}
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }}
            VITE_KEYCLOAK_REALM=${{ vars.VITE_KEYCLOAK_REALM }}
            VITE_KEYCLOAK_CLIENT_ID=${{ vars.VITE_KEYCLOAK_CLIENT_ID }}
            VITE_FILES_BASE=${{ vars.VITE_FILES_BASE }}

  deploy_to_server:
    runs-on: ubuntu-24.04
    needs: build-and-push
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.PROD_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull & restart via Docker Compose
        env:
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}  # ex: /home/voyages/front
          IMAGE: ghcr.io/${{ github.repository }} # netvolutionfr/voyages-front
          TAG: ${{ github.sha }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.PROD_SSH_PORT }}" \
            "${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}" "\
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \
            cd ${DEPLOY_DIR} && \
            docker compose pull && \
            docker compose up -d && \
            docker image prune -f && \"
            echo '== health 8082 ==' && \
              (curl -fsS http://127.0.0.1:8082/health || wget -qO- http://127.0.0.1:8082/health) >/dev/null \
                && echo 'health: OK'
            "
