name: Frontend CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint & Test (non bloquant temporairement)
        run: |
          npm run lint --if-present || true
          npm test --if-present -- --ci || true

      # (facultatif) build Node pour smoke-test du code
      - name: Build (CI)
        run: npm run build
        env:
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_KEYCLOAK_URL: ${{ vars.VITE_KEYCLOAK_URL }}
          VITE_KEYCLOAK_REALM: ${{ vars.VITE_KEYCLOAK_REALM }}
          VITE_KEYCLOAK_CLIENT_ID: ${{ vars.VITE_KEYCLOAK_CLIENT_ID }}
          VITE_FILES_BASE: ${{ vars.VITE_FILES_BASE }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,priority=800
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_API_BASE=${{ vars.VITE_API_BASE }}
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }}
            VITE_KEYCLOAK_REALM=${{ vars.VITE_KEYCLOAK_REALM }}
            VITE_KEYCLOAK_CLIENT_ID=${{ vars.VITE_KEYCLOAK_CLIENT_ID }}
            VITE_FILES_BASE=${{ vars.VITE_FILES_BASE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          # si l'image GHCR est privée, décommenter la ligne suivante
          # envs: PROD_GHCR_TOKEN
          script: |
            set -euo pipefail

            IMAGE="ghcr.io/netvolutionfr/voyages-front"
            TAG="${{ github.sha }}"

            cd "$HOME/front" || { echo "No ~/front"; exit 1; }

            # (si image privée) login GHCR côté serveur :
            # echo "${PROD_GHCR_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "== compose config résolu avec FRONT_TAG=${TAG} =="
            FRONT_TAG="${TAG}" docker compose config

            echo "== pull ${IMAGE}:${TAG} =="
            docker pull "${IMAGE}:${TAG}"

            echo "== up -d --pull always --force-recreate front =="
            FRONT_TAG="${TAG}" docker compose up -d --no-deps --pull always --force-recreate front

            echo "== ps après =="
            docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'

            echo "== logs récents =="
            docker logs --tail=80 voyages-front || true

            echo "== health check sur 8082 =="
            curl -fsS http://127.0.0.1:8082/health && echo "health: OK"
